ALTER TABLE shelf DROP CONSTRAINT IF EXISTS shelf_userid_fkey;

DROP TABLE IF EXISTS users; 
CREATE TABLE users (
  userId UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  username TEXT UNIQUE NOT NULL,
  email TEXT UNIQUE NOT NULL,
  googleId TEXT UNIQUE NOT NULL
);